# Use official Python image
FROM python:3.10-slim

# Set working directory inside container
WORKDIR /app

# Copy dependency files
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the project code into the container
COPY . .

# Automatically load .env
ENV PYTHONUNBUFFERED=1

# Default command to run your script
CMD ["python", "web.py"]
